### PR TITLE
Adds support for Ruby 3 / Sinatra 3

### PR DESCRIPTION
**Pull request by mandelbro**
This change bumps the versions of Ruby 3 and Sinatra 3

### CODE REVIEW

**Comment by wuputah** [comment]
heya, I dont have `w` bit here anymore (ironically, since that's why I originally moved it off of `@heroku`), but of course I have no incentive to maintain this anymore, and so maybe that's also fine with me. I'd be surprised if there isn't an internal fork, or something? I will use a spell slot to summon @schneems. 🪄

**Comment by mandelbro** [comment]
Thanks for the reply, we considered an internal fork but wanted to contribute to this repository in case it is still active, if that's not the case then please feel free to disregard.

**Comment by mandelbro** [comment]
Closing this and making a new PR

**Comment by schneems** [comment]
@wuputah I hope this github comment finds you well.

Can you give me release access on Rubygems? We deploy and use a private package version now (not rubygems) but it would probably be good if we can release to rubygems as well. Email is firstname dot lastname and the google mail .com address. You can add someone new via the `gem owner` command with `--add` and my email.

**Comment by wuputah** [comment]
You as well, it would be great to hang out sometime!

I've added you as owner.

**Comment by schneems** [comment]
@wuputah I've added some other Herokai and I removed you. I wish there was a rubygems "alumni" or something to recognize all your ownership efforts.

> You as well, it would be great to hang out sometime!

For sure! A radio coffee or easy tiger alumni hang would be sweet. It's been forever.

**Comment by wuputah** [comment]
not sure why removing me was "necessary" but whatever

**Comment by schneems** [comment]
Same reason Ed went through and removed access to this org. If your account was compromised then, yes...Herokai are still protected by using internally deployed software, but it's a weak chain link and it could get one of us locally if we forget to use the gem proxy or an unsuspecting 3rd party user who is using the gem.

FWIW I found someone to take over https://github.com/heroku/pg_lock and was blocked from transferring the repo to them or moving it into a different or to give them commit access. There are a few more "just incase" rules these days around access and security. Some are more founded than others.

**Comment by wuputah** [comment]
That's why this was moved off of `@heroku`. At least `rack-timeout` made it clear of the Salesforce orbit, I guess.

My Rubygems account has 2FA and a >16 character randomly generated password. "If your account was compromised" is a nonsense reason and I'm rather certain you do not question every single author on every single gem (and npm package, and…) used at Salesforce about the security of their accounts.

**Pull request closed without merging**
